### ISSUE TITLE
Window & Tab Support

### ISSUE THREAD

**Issue by briangonzalez** [eggplanetio/mert#5]
We could quite easily achieve window and tab support by nesting arrays in layouts.
- If nest level === 3, use windows.
- If nest level === 2, use tabs.
- If not nested, simply use panes.

``` yaml
# example .mertrc
layout:
  - 
    - 
      - echo "Window 1, Tab 1, Pane 1"
      - echo "Window 1, Tab 1, Pane 2"
    - 
      - echo "Window 1, Tab 2, Pane 1"

  - 
    - 
      - echo "Window 2, Tab 1, Pane 1"
```

@juancaldera thoughts?

**Comment by briangonzalez** [comment]
Work begun here: https://github.com/eggplanetio/mert/pull/9

**Comment by michaelmoussa** [comment]
@briangonzalez perhaps something more explicit would be better than a convention based on depth alone?

``` yaml
layout:
  -
    window: # open the stuff below here in a new window (Window 1)
    -
      tab: # open the stuff below here in a new tab (Window 1, Tab 1)
        - echo "Window 1, Tab 1, Pane 1" # "window" or "tab" not specified, defaults to "pane"
        - echo "Window 1, Tab 1, Pane 2" # "window" or "tab" not specified, defaults to "pane"
    -
      tab: # open the stuff below here in a new tab (Window 1, Tab 2)
        - echo "Window 1, Tab 2, Pane 1" # "window" or "tab" not specified, defaults to "pane"
  -
    window: # open the stuff below here in a new window (Window 2)
    - echo "Window 2, Tab 1, Pane 1" # "window" or "tab" not specified, defaults to "pane"
```

To address [the issue I raised](https://github.com/eggplanetio/mert/issues/8), with this configuration, I could do something like this:

``` yaml
layout:
  -
    tab: # open the stuff below here in a new tab in the current window
      - echo "Current Window, New Tab, Pane 1"
      - echo "Current Window, New Tab, Pane 2"
```

Or, if I just wanted to load all of that stuff in-place, maybe I could do:

``` yaml
layout:
  -
    pane: # replace the current active pane with all the stuff below
      - echo "Current Window, Current Tab, Pane 1"
      - echo "Current Window, Current Tab, Pane 2"
```

which would split the current pane, execute everything in the layout in the new pane, then close the original pane (which effectively replaces the currently active pane with the layout I want). This would be helpful if launching a new iTerm instance and starting mert - that way you don't have to go back and close the original pane/tab.

Probably a bit more complicated to implement, but I think it'd make the configurations more readable, and make it easier for the user to indicate their intent. What do you think?
